### ISSUE TITLE
Add a tests that highlight subtlety of typed streams

### ISSUE THREAD

**Issue by gmercer** [ajoberstar/ike.cljj#12]
As the tests are serving as the usage doco, could you add something simpler than but similar to the following

``` clojure
(deftest typed-stream-func
  (is ["0" "1" "2" "3" "4"]  
      (->
          (java.util.stream.IntStream/range 0 100)
          (.mapToObj (sam* java.util.function.IntFunction str))
          (.filter (sam* java.util.function.Predicate string?))
          (.limit 5)
          (.collect (java.util.stream.Collectors/toList)))
        ))
```

``` clojure
(deftest typed-stream-pred
  (is [1 3 5 7 9 ]
      (->
        (java.util.stream.LongStream/range 0 100)
        (.filter (sam* java.util.function.LongPredicate odd?))
        (.limit 5)
        (.boxed)
        (.collect (java.util.stream.Collectors/toList)))))
```

NB the `IntFunction` rather than `Function` and the `LongPredicate` rather than `Predicate`

**Comment by ajoberstar** [comment]
Hi Gavin, maybe I'm being dense, but could you explain what subtlety you'd like to highlight? These examples don't seem to be particular to ike.cljj, but more just general considerations for streams. Not sure if it's relevant to explain in my docs/tests since I'm presuming the user has knowledge of streams before they try using this library (maybe that should be more explicit).

**Comment by gmercer** [comment]
Hi Andrew,
My examples are over the top in terms of a ```sam*``` test. 
It's just that for a LongStream you can't just ```(sam* java.util.function.Predicate odd?)``` even though that seems quite reasonable.
I thought a simple example ( simpler than mine ) would show that ```sam*``` *can* do what you need but the type of stream you use might need an adjustment to your usage.
Agree not particular to ike.cljj but might help when someone gets  

```ClassCastException com.sun.proxy.$Proxy3 cannot be cast to java.util.function.LongPredicate```

if they saw an example in the tests 
Thanks for your time - feel free to close

**Comment by ajoberstar** [comment]
Does [this test](https://github.com/ike-tools/ike.cljj/blob/master/test/ike/cljj/stream_test.clj#L33) address that point? If that's in line with what you were thinking I may also add something to the readme to emphasize that point too.

**Comment by gmercer** [comment]
Ah yes, don't know why I didn't see that.
Something in the README would be handy
As you can see from the examples they were lifted from your discussions in the google group, got the ClassCast and ended up reading the Java API to resolve .
Thanks for great library.
